major & minor releases, with switches to define operations.
dryrun & dummy repos now separate options;
cvs tagging: rtag branch when necessary;
switch parser, help text, check we have version_major;
minor release not yet implemented,
  variable set as a subset of bumpmajor

diff --git a/dist/scripts/otterlace_release_major b/dist/scripts/otterlace_release_major
--- a/dist/scripts/otterlace_release_major
+++ b/dist/scripts/otterlace_release_major
@@ -2,7 +2,10 @@
 
 # Bumps version numbers which are stored in files.
 #
-# Creates tags in Git and CVS modules.
+# Creates tags in Git and CVS modules, acting (more or less) directly
+# on the central repositories.  That means you can run the current
+# devel tagging script against an existing release branch, treating
+# the release as data.
 #
 # Leaves repositories in a state from which you could VCS-export code
 # to build a specific release ($MAJOR-$MINOR)
@@ -25,17 +28,27 @@
 # We are then ready for new release & dev builds
 
 
+# The plan for bumping the minor version:
+#
+#   start on the "master" branch
+#
+#   we must obtain the current release
+#     subtract one from the apparent version_major
+#     checkout this release branch
+#
+#   on the existing release branch,
+#     minor version bump
+
+
 ensembl_cvs_repo=cvs.sanger.ac.uk/cvsroot/ensembl
 anacode_cvs_repo=cvs.internal.sanger.ac.uk:/repos/cvs/anacode
 ensembl_otter_git_repo=git:/repos/git/anacode/ensembl-otter
 
-# Could differ from what we're operating upon, but probably doesn't
-thisprog="$0 ($( cd $( dirname "$0") && git log -1 --format=%h ))"
-
-tmp_dir="$( mktemp -t -d "$( basename "$0" ).XXXXXX" )" || exit 1
-#dryrun=1
-#dryrun=dummy
-verbose=
+# Could differ from what we're operating upon, but often doesn't.
+#
+# Still we expect it to come out of a git working copy, and we don't
+# chase symlinks first.
+thisprog="$0 ($( cd $( dirname "$0") && git log -1 --format=%h ))" || exit 1
 
 
 # Dummy repositories for script testing.
@@ -76,9 +89,6 @@ _create_dummy_repos_cvs() {
     ensembl_cvs_repo="$dummies/ensembl"
     anacode_cvs_repo="$dummies/anacode"
     ensembl_otter_git_repo="$dummies/ens-ott.git"
-
-    printf "    We have fake repos, proceed without dryrun\n\n"
-    dryrun=
 }
 
 
@@ -107,16 +117,38 @@ sanity_check_version_minor_is_null() {
         # sanity check failed - bail
         exit 1
     } >&2
+    sanity_check_version_major_not_null
+}
+
+sanity_check_version_major_not_null() {
+    [ -n "$( config version_major )" ] || {
+        echo "version_major is null - weird"
+        echo "do we have dist/conf/ on this branch?"
+        git branch -v
+        exit 1
+    } >&2
 }
 
 set_variables_bumpmajor() {
     # these variables intentionally not local
-#            zmap_link="$( config "zmap_path" )"
+
+#    zmap_link="$( config "zmap_path" )"
 # unused - should it be used in the next line?
     zmap_path="$( readlink ~zmap/BUILD.DEVELOPMENT )"
-    version_major="$( config "version_major" )"
+
+    set_variables_bumpminor
     version_major_new="$( printf "%02d" "$(( $version_major + 1 ))" )"
-    version_minor="01"
+}
+
+set_variables_bumpminor() {
+    # these variables intentionally not local
+    sanity_check_version_major_not_null
+
+    version_major="$( config "version_major" )"
+    version_minor="$( printf "%02d" "$(( $( config version_minor ) + 1 ))" )"
+    # this works on master "56"."" -> "56"."01" for bumpmajor,
+    # and on a release branch "56"."01" -> "56"."02"
+
     release_branch="humpub-branch-${version_major}"
     release_tag="humpub-release-${version_major}-${version_minor}"
 }
@@ -127,6 +159,23 @@ git_update() {
     git clone -q -b master "$ensembl_otter_git_repo" ensembl-otter &&
     cd ensembl-otter &&
     sanity_check_version_minor_is_null &&
+
+    if [ "$do_op" = "major" ]; then
+        do_bumpmajor
+    elif [ "$do_op" = "minor" ]; then
+        do_bumpminor
+    else
+        echo "Puzzled: $do_op" >&2
+        false
+    fi &&
+
+    git push ${dryrun:+-n} origin master "$release_tag" "$release_branch" &&
+    # pushing master is not always necessary, but a no-op is safe
+
+    true
+}
+
+do_bumpmajor() {
     set_variables_bumpmajor &&
 
     # release branch and tags
@@ -147,11 +196,27 @@ git_update() {
     sed -i -e "/^version=/s/=.*/=${version_major_new}/" modules/Bio/Otter/Lace/Defaults.pm &&
     git commit -a -m "$( printf "Bump major version after release branch.\n\nDevelopment continues as version ${version_major_new};\nGenerated by %s\n" "$thisprog" )" &&
     git_show_maybe &&
-
-    git push ${dryrun:+-n} origin master "$release_tag" "$release_branch" &&
-
     true
 }
+
+# May update $bumprel
+do_bumpminor() {
+    local dev_major
+    if [ "$bumprel" = "last" ]; then
+        dev_major="$( config version_major )"
+        bumprel="$( printf "%02d" "$(( $dev_major - 1 ))" )"
+        echo " : Current development is v$dev_major"
+    fi
+
+    git checkout "humpub-branch-$bumprel" &&
+    echo " : Using release branch v$bumprel" &&
+
+    set_variables_bumpminor &&
+
+    echo "TODO: Minor version bump not yet implemented" >&2
+    false
+}
+
 
 git_show_maybe() {
     if [ -n "$verbose" ]; then
@@ -166,12 +231,17 @@ git_listrefs_maybe() {
     fi
 }
 
+# On one CVS repo, tag the release
+# and if we did set_variables_bumpmajor,
+#   also label the branch at that point
 cvs_update_repo() {
     local repo module
     repo="$1"
     module="$2"
     ${dryrun:+echo DRYRUN:} cvs -d "$repo" -q rtag    -rHEAD           "$release_tag"    "$module" &&
-    ${dryrun:+echo DRYRUN:} cvs -d "$repo" -q rtag -b -r"$release_tag" "$release_branch" "$module" &&
+    if [ -n "$version_major_new" ]; then
+        ${dryrun:+echo DRYRUN:} cvs -d "$repo" -q rtag -b -r"$release_tag" "$release_branch" "$module"
+    fi &&
     true
 }
 
@@ -182,13 +252,106 @@ cvs_update() {
 }
 
 
+# Sets variables.  May exit.
+parse_switches() {
+    local sw
+    while [ $# -gt 0 ]; do
+        sw=$1
+        shift
+        case $sw in
+            --major) _setop major   ;;
+            --minor) _setop minor
+                bumprel=last
+                case $1 in
+                    [0-9][0-9] | [0-9][0-9][0-9] )
+                        bumprel=$1
+                        shift
+                        ;;
+                esac
+                ;;
+            -v | --verbose)  verbose=1      ;;
+            -D | --dummy)    with_dummy=1   ;;
+            -n | --dryrun)   dryrun=1       ;;
+            -h | --help)
+                show_syntax
+                exit 0
+                ;;
+            *)
+                echo "Unknown option '$sw', try -h"
+                exit 1
+                ;;
+        esac
+    done
+}
+
+_setop() {
+    if [ -n "$do_op" ]; then
+        echo "Already planning to do '$do_op', cannot also do '$1'" >&2
+        exit 1
+    fi
+    do_op=$1
+}
+
+
+show_syntax() {
+    echo "Syntax: $0 [ -v ] [ -D ] [-n] < --major | --minor [NN] >"
+    cat <<MSG
+
+Necessary switches - one of
+
+  --major      Tag new release branch and matching .01 minor release.
+
+  --minor NN   Tag new minor release on the existing branch for major
+               version NN.
+
+  --minor      Tag new minor release on the latest release branch.
+               Uses (current master's major release number) minus one.
+
+
+Optional switches:
+
+  -D
+  --dummy    Make in TMPDIR some local CVS and Git repositories,
+             and use these instead of the real ones.
+
+  -n
+  --dryrun   Perform noisy no-ops instead of VCS commands.
+
+  -v
+  --verbose  More noise
+
+
+This is $thisprog
+
+MSG
+}
+
+
 main() {
+    local tmp_dir
+#    echo "Doing these: do_op=$do_op bumprel=$bumprel verbose=$verbose dryrun=$dryrun with_dummy=$with_dummy"
 
-[ "$dryrun" = "dummy" ] && _create_dummy_repos_cvs
+    if [ -z "$do_op" ]; then
+        echo "Missing a necessary option"
+        show_syntax >&2
+        return 4
+    fi
 
-( cd "$tmp_dir" &&
-    git_update &&
-    cvs_update &&
-    true ) &&
-rm -rf -- "$tmp_dir" &&
-true # success
+    tmp_dir="$( mktemp -t -d "$( basename "$0" ).XXXXXX" )" || exit 1
+
+    [ -n "$with_dummy" ] && _create_dummy_repos_cvs
+
+    ( cd "$tmp_dir" &&
+        git_update &&
+        cvs_update &&
+        true ) &&
+
+    rm -rf -- "$tmp_dir" &&
+    true # success
+}
+
+
+parse_switches "$@"
+
+main
+exit $?
