dist/scripts/tag_otterlace_release replaces otterlace_release_minor,   implement do_bumpminor; permit re-use of dummy repos by defining $dummies,  (put cvslocks down a level to avoid confusing me again)

diff --git a/dist/scripts/tag_otterlace_release b/dist/scripts/tag_otterlace_release
--- a/dist/scripts/tag_otterlace_release
+++ b/dist/scripts/tag_otterlace_release
@@ -53,14 +53,12 @@ thisprog="$0 ($( cd $( dirname "$0") && git log -1 --format=%h ))" || exit 1
 
 # Dummy repositories for script testing.
 _create_dummy_repos_cvs() {
-    local dummies
-
     dummies="$( mktemp -t -d DUMMY_REPOS.XXXXXX )" || {
         echo Failed to mktemp -d >&2
         # Serious because caller does not want to do real operations
         exit 1
     }
-    printf "\n*** Creating and running with dummy repos in %s\n    these will NOT be cleaned up\n" "$dummies"
+    printf "\n*** Creating and running with dummy repos,\n    dummies=%s\n    these will NOT be cleaned up\n    you can use them again by setting the variable\n\n" "$dummies"
 
     # Make fake repos
     #  ens-ott is deliberately != ensembl-otter
@@ -71,18 +69,30 @@ _create_dummy_repos_cvs() {
         cd "$dummies"
         # set -e, cd : local to the ( ... )
 
-        mkdir -p $dummies/{ensembl/ensembl-analysis,anacode}
+        mkdir -p $dummies/{ensembl/ensembl-analysis,anacode,cvslock}
         git clone -q --bare "$ensembl_otter_git_repo" ens-ott.git
 
         cd "$dummies/anacode"
         scp -rpq ${anacode_cvs_repo}/{CVSROOT,PerlModules,humscripts} .
         # intcvs1 uses a separate LockDir, which we don't have
-        LKDIR="$dummies" perl -i~ -pe 's{LockDir=.*}{LockDir=$ENV{LKDIR}}' CVSROOT/config
+        LKDIR="$dummies/cvslock" perl -i~ -pe 's{LockDir=.*}{LockDir=$ENV{LKDIR}}' CVSROOT/config
 
         cvs -d "$dummies/ensembl" init
         # provide one file, to be tagged
         cp -pR "$dummies/ensembl"/{CVSROOT/config\,v,ensembl-analysis}
         )
+}
+
+_use_dummy_repos_cvs() {
+    if [ -z "$dummies" ]; then
+        _create_dummy_repos_cvs
+    else
+        [ -d "$dummies/ens-ott.git" ] &&
+        printf "\n*** Running with existing dummy repos in %s\n" "$dummies"
+    fi || {
+        echo "Failed while using dummy repos" >&2
+        exit 1
+    }
 
     # Replace the "upstream" repositories, so we can perform real VCS
     # operations on them.
@@ -198,8 +208,8 @@ do_bumpmajor() {
     config_set version_minor "$version_minor" &&
     config_set zmap_path "$zmap_path" &&
     git commit -a -m "$( printf "New release branch.\n\nNext release will be ${release_tag};\nZMap is %s\nGenerated by %s\n" "$zmap_path" "$thisprog" )" &&
-    git_show_maybe &&
     git tag "$release_tag" &&
+    git_show_maybe &&
     git_listrefs_maybe &&
     config_show_maybe &&
 
@@ -231,9 +241,14 @@ do_bumpminor() {
 
     set_variables_bumpminor &&
 
-    echo "TODO: Minor version bump not yet implemented" >&2
+    # release tag
+    config_set version_minor "$version_minor" &&
+    git commit -a -m "$( printf "New release tag %s\n\nZMap is %s\nGenerated by %s\n" "$release_tag" "$zmap_path" "$thisprog" )" &&
+    git tag "$release_tag" &&
+    git_show_maybe &&
+    git_listrefs_maybe &&
     config_show_maybe &&
-    false
+    true
 }
 
 
@@ -358,7 +373,7 @@ main() {
 
     tmp_dir="$( mktemp -t -d "$( basename "$0" ).XXXXXX" )" || exit 1
 
-    [ -n "$with_dummy" ] && _create_dummy_repos_cvs
+    [ -n "$with_dummy" ] && _use_dummy_repos_cvs
 
     ( cd "$tmp_dir" &&
         git_update &&
